type IconKind =
  | "person"
  | "link"
  | "calendar"
  | "more"
  | "star"
  | "people"
  | "pencil"
  | "arrowDown"
  | "thumbDown"
  | "thumbUp"
  | "bad"
  | "disappointing"
  | "average"
  | "satisfied"
  | "verySatisfied"
  | "info"
  | "arrowLeft"
  | "arrowRight"
  | "arrowDropDown"
  | "arrowDropUp"
  | "arrowRenew"
  | "check"
  | "menu"
  | "close"
  | "githubLogo"
  | "notificationBell"
  | "search"
  | "add"
  | "delete"
  | "edit"
  | "control";

export default IconKind;
