# .github/workflows/pr-stats.yml
name: PR Stats and Notifications

on:
  pull_request:
    types:
      - closed  # PR이 닫힐 때 트리거

jobs:
  pr-stats-job:
    if: github.event.pull_request.merged == true  # PR이 merge된 경우에만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Python 3.x 버전 사용

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk requests

      - name: Run PR Stats
        uses: "naver/pr-stats@v1.0.0"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze PR Stats and Notify
        run: |
          python .github/scripts/pr-stats.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_HTML_URL: ${{ github.event.pull_request.html_url }}
          ASSIGNEE: ${{ github.event.pull_request.assignee.login }}
